Update caddy.yml

diff --git a/.github/workflows/caddy.yml b/.github/workflows/caddy.yml
--- a/.github/workflows/caddy.yml
+++ b/.github/workflows/caddy.yml
@@ -168,9 +168,32 @@ jobs:
           else
             # echo "Success: ${TARGET_HTTP_CODE}"
             echo -e "\033[1;40;92m$(date '+%F %T') === Success: \033[0m\e[30;48;5;2m${TARGET_HTTP_CODE}\e[0m"
-            # gh release delete "${TARGET_TAG}" -y --cleanup-tag
-            gh release delete "${TARGET_TAG}" --yes --cleanup-tag
+            # gh release delete "${TARGET_TAG}" -y --cleanup-tag || echo -e "\033[1;40;96m$(date '+%F %T') === Fail: \033[0m\e[30;48;5;1m${TARGET_TAG} release not found\e[0m"
+            gh release delete "${TARGET_TAG}" --yes --cleanup-tag || echo -e "\033[1;40;96m$(date '+%F %T') === Fail: \033[0m\e[30;48;5;1m${TARGET_TAG} release not found\e[0m"
             # echo "Target tag or release ${TARGET_TAG} deleted Complete!"
+
+            while true; do
+            # until false; do
+            echo -e "\e[30;48;5;12m$(date '+%F %T') === check release exist\e[0m"
+
+            TARGET_HTTP_CODE_TAG=$(curl -sI -w "%{http_code}" -o "/dev/null" \
+              -H "Authorization: Bearer ${GH_TOKEN}" \
+              https://api.github.com/repos/${{ github.repository }}/git/ref/tags/${TARGET_TAG} )
+  
+            TARGET_HTTP_CODE_RELEASE=$(curl -sI -w "%{http_code}" -o "/dev/null" \
+              -H "Authorization: Bearer ${GH_TOKEN}" \
+              https://api.github.com/repos/${{ github.repository }}/releases/tags/${TARGET_TAG} )
+
+            if [[ ${TARGET_HTTP_CODE_TAG} == 404 && ${TARGET_HTTP_CODE_RELEASE} == 404 ]] &>/dev/null; then
+            echo -e "\e[30;48;5;14m$(date '+%F %T') === release is no exist ready to upload\e[0m"
+            break 49
+            else
+            echo -e "\e[30;48;5;11m$(date '+%F %T') === release exist retrying\e[0m"
+            fi
+
+            sleep 3
+            done
+
             echo -e "\033[1;40;94m$(date '+%F %T') === Target tag or release \e[0m\e[30;48;5;4m${TARGET_TAG}\e[0m\033[1;40;94m deleted Complete! \033[0m"
           fi
 
